version: '3'
services:
  members-only: 
    image: 262200957002.dkr.ecr.us-east-1.amazonaws.com/members-only:latest
    ports:
     - 3000:3000
    environment:
     - MONGO_URI=mongodb://admin:pass@mongodb
     - ADMIN_PASSCODE= 12345
     - MEMBER_PASSCODE= 12345
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
     - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local